# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somali_german_dictionary',
            name='German',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='German'),
        ),
    ]
